# Generated by Django 4.2.23 on 2025-06-25 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('is_published', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=50)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('images', models.JSONField(blank=True, default=dict)),
                ('packages', models.JSONField(blank=True, default=list)),
                ('additional_members_config', models.JSONField(blank=True, default=dict)),
                ('food_preference_config', models.JSONField(blank=True, default=dict)),
                ('faq', models.JSONField(blank=True, default=list)),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='hosts.host')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
