# Generated by Django 5.2.3 on 2025-06-29 13:40

import django.db.models.deletion
import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('cover', 'Cover Image'), ('thumbnail', 'Thumbnail Image'), ('square', 'Square Image')], max_length=20)),
                ('image', models.ImageField(upload_to=events.models.event_image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_images', to='events.event')),
            ],
            options={
                'unique_together': {('event', 'image_type')},
            },
        ),
    ]
