# Generated by Django 5.2.3 on 2025-06-29 16:01

import django.db.models.deletion
import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eventimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(max_length=20, unique=True)),
                ('user_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('member_count', models.IntegerField(default=1)),
                ('selected_package', models.JSONField(blank=True, default=dict)),
                ('food_preference', models.CharField(blank=True, max_length=100)),
                ('additional_members', models.JSONField(blank=True, default=list)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to=events.models.booking_qr_path)),
                ('status', models.CharField(choices=[('Not Scanned', 'Not Scanned'), ('Checked In', 'Checked In'), ('Checked Out', 'Checked Out')], default='Not Scanned', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='events.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
