# Generated by Django 4.2.23 on 2025-06-30 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
        migrations.AddField(
            model_name='booking',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
    ]
