# Generated by Django 4.2.23 on 2025-07-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_booking_status_booking_is_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='limit',
            field=models.IntegerField(blank=True, help_text='Maximum number of registrations allowed (leave blank for unlimited)', null=True),
        ),
    ]
