# Generated by Django 4.2.23 on 2025-07-01 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='limit',
        ),
    ]
