# Generated by Django 4.2.23 on 2025-07-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_emergencycontact_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
